name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: client
    - run: npm install
    - name: react-test-scripts
      run: npm test
