name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: |
        cd client
        npm install
    - name: react-test-scripts
      run: |
        cd client
        npm test